=pod

=encoding UTF-8

=head1 NAME

Log::Log4perl::Appender::Redis - ...

=head1 VERSION

version 0.001

=head1 SYNOPSIS

    ...

=head1 DESCRIPTION

...

=head1 METHODS

=head2 new(%options)

...

=head2 log(%params)

...

=for Pod::Coverage DESTROY

=head1 SEE ALSO

=over 4

=item *

L<Log::Log4perl::Appender>

=item *

L<Log::Log4perl::Appender::Stomp> (used as a base for this module)

=item *

L<Redis>

=back

=head1 AUTHOR

Stanislaw Pusep <stas@sysd.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013 by Stanislaw Pusep.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

